### ISSUE TITLE
Should this repo exist?

### ISSUE THREAD

**Issue by myers** [basho/mochiweb#13]
mochiweb has moved to github.  Perhaps the changes in this repo should be merged?

https://github.com/mochi/mochiweb

**Comment by samlecuyer** [comment]
at the very least, the link in the repo header should be updated.

**Comment by bsparrow435** [comment]
We just finished grabbing a bunch of upstream changes back into our mochiweb. I'm updating the repo header to point at mochi/mochiweb so it's clear that this is a fork of that canonical repo.
