### ISSUE TITLE
Support recbuf option.

### ISSUE THREAD

**Issue by ksauzz** [basho/mochiweb#18]
It's often necessary to increase receive buffer size in some use-cases such as a large query including url-encoded multibyte characters with Riak Search. However, [it's 8192 as "hard code" now.](https://github.com/basho/mochiweb/blob/ade2a9b29a11034eb550c1d79b4f991bf5ca05ba/include/internal.hrl#L2) Original mochiweb repo has the changes to expose this option:

https://github.com/mochi/mochiweb/pull/134
https://github.com/mochi/mochiweb/pull/154

see: zd#11091

**Comment by bsparrow435** [comment]
Thank you! We are currently working on brining in the upstream mochi changes.
